name: Run Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        laravel: ['10.*', '11.*', '12.*']
        php: ['8.2', 8.3, '8.3', '8.4']
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*
            testbench: 9.*
          - laravel: 12.*
            testbench: 10.*
        exclude:
          - laravel: 10.*
            php: 7.3
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 8.3
          - laravel: 11.*
            php: 7.3
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1
          - laravel: 12.*
            php: 7.3
          - laravel: 12.*
            php: 7.4
          - laravel: 12.*
            php: 8.0
          - laravel: 12.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, curl, pcntl, pdo, sqlite, pdo_sqlite, iconv, xdebug, mysqlnd, bcmath, bz2, dba, enchant, gd, gmp, igbinary, imagick, imap, intl, ldap, memcache, mongodb, msgpack, mysqli, odbc, pdo_dblib, pdo_firebird, pdo_mysql, pdo_odbc, pdo_pgsql, pdo_sqlsrv, pgsql, pspell, redis, snmp, soap, sqlsrv, tidy, yaml, zmq, memcached, ds
          coverage: none

      - name: Debug PHP Setup
        run: |
          php -v
          php -m

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "symfony/console:>=4.3.4" "mockery/mockery:^1.3.2" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Migrate PHPUnit Configuration
        run: ./vendor/bin/phpunit --migrate-configuration || true

      - name: Execute tests
        run: |
          vendor/bin/phpunit --no-coverage
